import { v4 as uuidv4 } from 'uuid';

export const majorProjectsData = [
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject13.jpg',
    title: 'TAWEELAH REVERSE OSMOSIS. INDEPENDENT WATER PROJECT',
    endUser: 'TAWEELAH RO DESALINATION COMPANY',
    client: 'ABENGOA',
    scope: `REPAIR/MODIFICATION & FABRICATION OF SPOOLS, REINFORCEMENT PAID FOR 22"X16" BRACH - HP RING BYPASS LINE - RO 1 & 2, MATERIAL PROCUREMENT / WELD REPIAR OF DAMAGED PLUGS`,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: 'CONTRACTOR',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject14.jpg',
    title: 'HOT TAPPING PROJECT IN INDIA',
    endUser: 'TD WILLIAMSON',
    client: 'TD WILLIAMSON',
    scope: `HYDRO TEST & CERTIFICATOIN OF 48"X600# SANDWICH VALVE`,
    jobNumber: 'XV-22-488',
    role: 'CONTRACTOR',
    year: '2011',
  },
  ,
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject15.jpg',
    title: 'NATIONAL GAS DIVISION CITY GAS PROJECT',
    endUser: 'ADNOC LNG',
    client: 'ADNOC INTERNATIONAL GULF LLC',
    scope: `HYDROSTATIC TESTING AND CERTIFICATION`,
    jobNumber: 'XV-20-175',
    role: 'CONTRACTOR',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject16.jpg',
    title: 'RO WATER PLANT FOR JEBEL ALI AL. SMELTER PROJECT',
    endUser: 'TAWEELAH RO DESTINATION COMPANY',
    client: 'ARFLU INDUSTRIAL VALVES',
    scope: `REPAIR OF (10"-22") PLUG VALVES AT SITE`,
    jobNumber: 'XV-21-344, XV-21-367, XV-21-388, XV-21-400, XV-22-448',
    role: 'CONTRACTOR',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject17.jpg',
    title: 'POWER AND STEM INTEGRATION',
    endUser: 'EGA',
    client: 'FLOWSERVE',
    scope: `DRILLING/ARRANGE TEST SETUP/ SHELL TEST ON 20"X1500# GATE VALVES-ACCEV EQUALIZING VALVES INSTALLATION`,
    jobNumber: 'XV-22-509',
    role: 'CONTRACTOR',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject18.jpg',
    title: 'BUIFD PROJECT',
    endUser: 'ADNOC ONSHORE',
    client: 'FZV GROUP / TR',
    scope: `VALVE REPAIR AT MOI WORKSHOP & VALVE PAINT DAMAGE REPAIR AT SITE`,
    jobNumber: 'XV-23-608',
    role: 'CONTRACTOR',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject19.jpg',
    title: 'BARAKAH LRWS VESSELS SHIELDING & WELDING PROJECT',
    endUser: 'BNPP',
    client: 'ATKINS',
    scope: `STEEL FABRICATION WORKS - FABRICATION OF VESSELS SHIELDING & WELD PALLET WELDMENT - 2 SETS - 12 EACH`,
    jobNumber: 'XF-22-004',
    role: 'CONTRACTOR',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject20.jpg',
    title: '6000019117 - BLANKET CONTRACT',
    endUser: 'ADNOS GAS PROCESSING',
    client: 'ADNOC GAS PROCESSING',
    scope: `6000019117 - VALVE REFURBISHMENT AT ALL AGP SITES`,
    jobNumber: 'XV-22-500',
    role: 'CONTRACTOR',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject21.jpg',
    title: 'HALIBA DEVELOPMENT PROJECT',
    endUser: 'AL DHAFRA PETROLEUM',
    client: 'LTHE',
    scope: `HALIBA DEVELOPMENT PROJECT - VARIOUS VALVES PRESSURE TESTING & CERTIFICATION - 3000+NOs`,
    jobNumber: 'XV-19-0010',
    role: 'CONTRACTOR',
    year: '2011',
  },
  // {
  //   id: uuidv4(),
  //   img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject9.jpg',
  //   title: 'Fabrication of Jackets',
  //   client: 'Al Jaber Engineering',
  //   scope: 'Erection of Scaffolding for the fabrication of Jackets',
  //   role: 'Tech. Support in the form of MANPOWER',
  //   year: '2005',
  // },
  // {
  //   id: uuidv4(),
  //   img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject10.jpg',
  //   title: 'Repair,Refurbishment and Testing of the Valve',

  //   client: 'Al Mazroui Engineering Co.LLC',
  //   scope:
  //     'Repair,Refurbishment,Assembly of complete valve, pressure testing of the valve.',
  //   role: 'CONTRACTOR',
  //   year: '2009',
  // },
  // {
  //   id: uuidv4(),
  //   img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject11.jpg',
  //   title: 'SHUT DOWN MAINTENANCE',
  //   client: 'WOOD GROUP',
  //   scope:
  //     'Providing valve technicians,Instrument /Control valveTechnicians,PSV Technicians',
  //   role: 'CONTRACTOR',
  //   year: '2010',
  // },
  // {
  //   id: uuidv4(),
  //   img: '/images/ProjectsPage/Projects/MajorProjects/MajorProject12.jpg',
  //   title: 'Refurbishment of 42 GATE VALVE',
  //   client: 'VALVITALIA (ADMA)',
  //   scope:
  //     'Weld overlay on Gate,Machining lapping ,Assembly,Pressure Testing of Valve',
  //   role: 'CONTRACTOR',
  //   year: '2010',
  // },
];
