import { v4 as uuidv4 } from 'uuid';

export const recentProjectsData = [
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/RecentProjects/RecentProject11.jpg',
    title: 'HYDRAULIC BOLT TORQUING & TENSIONING',
    endUser: 'Custody transfer Skid',
    client: 'EMERSON',
    scope: `Flange bolt torquing -1 5/8”, 600#  Flanges,  size for hydro testing and final assembly`,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: 'Provision of manpower and equipment to perform service',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/RecentProjects/RecentProject12.jpg',
    title: ' PETROFAC/ASTRA ENGINEERING ',
    endUser: 'Custody transfer Skid',
    client: ' PETROFAC/ASTRA ENGINEERING ',
    scope: ` HABSHAN-3 FLARE GAS RECOVERY -64” FLARE HEADER TIE IN BOLT TORQUING`,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: 'Provision of manpower and equipment to perform service',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/RecentProjects/RecentProject13.jpg',
    title: 'ADNOC OFFSHORE/ AL RAHA MECHANICAL EQUIPMENT',
    endUser: 'Custody transfer Skid',
    client: 'ADNOC OFFSHORE/ AL RAHA MECHANICAL EQUIPMENT',
    scope: `Hub  flanged end Valves- De torquing, valve removal, flange facing, new valve installation at SARB plant, ZIRKU`,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: 'Provision of manpower and equipment to perform service',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/RecentProjects/RecentProject14.jpg',
    title: '18” Kicker line replacement- GPF LP Flare header- ZCC. MOI ',
    endUser: 'Custody transfer Skid',
    client: 'ADNOC OFFSHORE',
    scope: `Cold cutting machines with operator mobilization (18” to 24” range)`,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: 'Provision of manpower and equipment to perform service',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/RecentProjects/RecentProject15.jpg',
    title: ' TOP DRIVE- DRILLING SHAFT PLUG REMOVAL.',
    endUser: 'Custody transfer Skid',
    client: 'NOV AL MANSOORI',
    scope: `Cold cutting machines with operator mobilization (6-10” range)`,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: 'Provision of manpower and equipment to perform service',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/RecentProjects/RecentProject16.jpg',
    title: '46” CONDESATE  UNIT-DAS ISLAND',
    endUser: 'Custody transfer Skid',
    client: 'ADNOC OFFSHORE',
    scope: `2”,10” ,24” & 46”- Flanges RF machining & RTJ Groove making machining.`,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: 'Providing equipment and manpower for performing flange facing services.',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/RecentProjects/RecentProject17.jpg',
    title: 'Pipe flange facing & Groove making – 1.2 mtrs in diameter',
    endUser: 'Custody transfer Skid',
    client: 'Fujairah Oil terminal LLC',
    scope: `Flange groove making underway.`,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: 'Providing equipment and manpower for performing flange facing services.',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/RecentProjects/RecentProject18.jpg',
    title: 'INSTALLATION OF MOTORZIED VALVES AND PIPING',
    endUser: 'Custody transfer Skid',
    client: ' ETISALAT  DATA CENTRE',
    scope: `Diesel fuel lines with motorized valves and isolation ball valves shop fabrication and installation at site- 48 Nos’ Valve replacement.`,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: 'Diesel fuel lines with motorized valves and isolation ball valves shop fabrication and installation at site- 48 Nos’ Valve replacement.',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/RecentProjects/RecentProject19.jpg',
    title: 'AISI 4130 SPOOLS FABRICATION & HYDROTESTING',
    endUser: 'Custody transfer Skid',
    client: 'CONTRACTING & TRADING COMPANY LLC',
    scope: `6” Piping spools – Fabrication drawings , Spool fabrication, NDT, Blasting & Painting `,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: '6” Piping spools – Fabrication drawings , Spool fabrication, NDT, Blasting & Painting ',
    year: '2011',
  },
  {
    id: uuidv4(),
    img: '/images/ProjectsPage/Projects/RecentProjects/RecentProject20.jpg',
    title: 'HYDRAULIC FLUSHING & PRESSURE TESTING',
    endUser: 'Custody transfer Skid',
    client: 'E & I EMIRATES ',
    scope: `Well Hook up activities instrumentation tubing hydraulic flushing- ADNOC offshore.`,
    jobNumber: 'XF-22-002, XF-22-001, XV-22-507',
    role: 'Manpower & Equipment provision for flushing and pressure testing ',
    year: '2011',
  },
];
